import type { Metadata } from "next";
import { Geist, Geist_Mono, Konkhmer_Sleokchher } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import NavComponent from "@/components/nav";
import FooterComponent from "@/components/footer";
import "./globals.css";

const konkhmer_Sleokchher = Konkhmer_Sleokchher({
  weight: '400',
  style: ['normal'],
  subsets: ['latin'],
  display: 'block',
})

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${konkhmer_Sleokchher.className} antialiased h-screen`}>
        <NavComponent />
        {children}
        <Toaster />

      <FooterComponent />
      </body>
    </html>
  );
}
